export type All = {
	signer: number;
	uri: string;
	tokenid: string;
	spender: string;
	holder: string;
	address: string;
	from: string;
	to: string;
	value: number;
	currvalue: number;
	newvalue: number;
	year: number;
	month: number;
	quantity: number;
	min: number;
	max: number;
	role: string;
	adminRole: string;
};
