/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../common";
import type {
  AddressUtils,
  AddressUtilsInterface,
} from "../../utils/AddressUtils";

const _abi = [
  {
    inputs: [],
    name: "AddressUtils__InsufficientBalance",
    type: "error",
  },
  {
    inputs: [],
    name: "AddressUtils__NotContract",
    type: "error",
  },
  {
    inputs: [],
    name: "AddressUtils__SendValueFailed",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220e36a045f868a692ed1693896b0810539ed12cd36536425fba9babcb74f04759464736f6c63430008110033";

type AddressUtilsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: AddressUtilsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class AddressUtils__factory extends ContractFactory {
  constructor(...args: AddressUtilsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<AddressUtils> {
    return super.deploy(overrides || {}) as Promise<AddressUtils>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): AddressUtils {
    return super.attach(address) as AddressUtils;
  }
  override connect(signer: Signer): AddressUtils__factory {
    return super.connect(signer) as AddressUtils__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AddressUtilsInterface {
    return new utils.Interface(_abi) as AddressUtilsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AddressUtils {
    return new Contract(address, _abi, signerOrProvider) as AddressUtils;
  }
}
