/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../common";
import type { UintUtils, UintUtilsInterface } from "../../utils/UintUtils";

const _abi = [
  {
    inputs: [],
    name: "UintUtils__InsufficientHexLength",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122075a572e74561653e6f62be2fbb3268d81e5b88e11ec6f8a2d28810b0f03819a764736f6c63430008110033";

type UintUtilsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: UintUtilsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class UintUtils__factory extends ContractFactory {
  constructor(...args: UintUtilsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<UintUtils> {
    return super.deploy(overrides || {}) as Promise<UintUtils>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): UintUtils {
    return super.attach(address) as UintUtils;
  }
  override connect(signer: Signer): UintUtils__factory {
    return super.connect(signer) as UintUtils__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): UintUtilsInterface {
    return new utils.Interface(_abi) as UintUtilsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): UintUtils {
    return new Contract(address, _abi, signerOrProvider) as UintUtils;
  }
}
