call npx hardhat clean
call npx hardhat compile
call npx hardhat test
call npx hardhat coverage
call npx hardhat compile
call npx hardhat test
call npx hardhat size-contracts
call npx hardhat compile
call npx hardhat export-abi
call npx hardhat compile
