/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface ArexaPlatformAdminFacetInterface extends utils.Interface {
  functions: {
    "buyArexaTokenAdmin(address,uint128,uint8,uint16)": FunctionFragment;
    "buyEdgeSubscriptionAdmin(address,uint32,uint16)": FunctionFragment;
    "buyMagic100TokenAdmin(address,uint16)": FunctionFragment;
    "buyOracleSubscriptionAdmin(address,uint32,uint16)": FunctionFragment;
    "buySubscriptionAdmin(address,uint256,uint32,uint16)": FunctionFragment;
    "buyTraderTokenAdmin(address,uint128,uint8,uint16)": FunctionFragment;
    "createSubscription(uint256,uint16,uint8,uint256,uint256,uint256)": FunctionFragment;
    "getArexaTokenPool(uint8)": FunctionFragment;
    "payArexaTokenFromPool(uint8,address,uint32)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "buyArexaTokenAdmin"
      | "buyEdgeSubscriptionAdmin"
      | "buyMagic100TokenAdmin"
      | "buyOracleSubscriptionAdmin"
      | "buySubscriptionAdmin"
      | "buyTraderTokenAdmin"
      | "createSubscription"
      | "getArexaTokenPool"
      | "payArexaTokenFromPool"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "buyArexaTokenAdmin",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "buyEdgeSubscriptionAdmin",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "buyMagic100TokenAdmin",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "buyOracleSubscriptionAdmin",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "buySubscriptionAdmin",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "buyTraderTokenAdmin",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createSubscription",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getArexaTokenPool",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "payArexaTokenFromPool",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "buyArexaTokenAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buyEdgeSubscriptionAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buyMagic100TokenAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buyOracleSubscriptionAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buySubscriptionAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buyTraderTokenAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getArexaTokenPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "payArexaTokenFromPool",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ArexaPlatformAdminFacet extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ArexaPlatformAdminFacetInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    buyArexaTokenAdmin(
      toAccount: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      valueType: PromiseOrValue<BigNumberish>,
      discountPercent: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    buyEdgeSubscriptionAdmin(
      toAccount: PromiseOrValue<string>,
      quantity: PromiseOrValue<BigNumberish>,
      discountPercent: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    buyMagic100TokenAdmin(
      toAccount: PromiseOrValue<string>,
      discountPercent: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    buyOracleSubscriptionAdmin(
      toAccount: PromiseOrValue<string>,
      quantity: PromiseOrValue<BigNumberish>,
      discountPercent: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    buySubscriptionAdmin(
      toAccount: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      quantity: PromiseOrValue<BigNumberish>,
      discountPercent: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    buyTraderTokenAdmin(
      toAccount: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      valueType: PromiseOrValue<BigNumberish>,
      discountPercent: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createSubscription(
      tokenType: PromiseOrValue<BigNumberish>,
      year: PromiseOrValue<BigNumberish>,
      month: PromiseOrValue<BigNumberish>,
      quantity: PromiseOrValue<BigNumberish>,
      min: PromiseOrValue<BigNumberish>,
      max: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getArexaTokenPool(
      _tokenType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { total: BigNumber; sold: BigNumber }>;

    payArexaTokenFromPool(
      poolType: PromiseOrValue<BigNumberish>,
      account: PromiseOrValue<string>,
      quantity: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  buyArexaTokenAdmin(
    toAccount: PromiseOrValue<string>,
    value: PromiseOrValue<BigNumberish>,
    valueType: PromiseOrValue<BigNumberish>,
    discountPercent: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  buyEdgeSubscriptionAdmin(
    toAccount: PromiseOrValue<string>,
    quantity: PromiseOrValue<BigNumberish>,
    discountPercent: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  buyMagic100TokenAdmin(
    toAccount: PromiseOrValue<string>,
    discountPercent: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  buyOracleSubscriptionAdmin(
    toAccount: PromiseOrValue<string>,
    quantity: PromiseOrValue<BigNumberish>,
    discountPercent: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  buySubscriptionAdmin(
    toAccount: PromiseOrValue<string>,
    tokenId: PromiseOrValue<BigNumberish>,
    quantity: PromiseOrValue<BigNumberish>,
    discountPercent: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  buyTraderTokenAdmin(
    toAccount: PromiseOrValue<string>,
    value: PromiseOrValue<BigNumberish>,
    valueType: PromiseOrValue<BigNumberish>,
    discountPercent: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createSubscription(
    tokenType: PromiseOrValue<BigNumberish>,
    year: PromiseOrValue<BigNumberish>,
    month: PromiseOrValue<BigNumberish>,
    quantity: PromiseOrValue<BigNumberish>,
    min: PromiseOrValue<BigNumberish>,
    max: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getArexaTokenPool(
    _tokenType: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber] & { total: BigNumber; sold: BigNumber }>;

  payArexaTokenFromPool(
    poolType: PromiseOrValue<BigNumberish>,
    account: PromiseOrValue<string>,
    quantity: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    buyArexaTokenAdmin(
      toAccount: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      valueType: PromiseOrValue<BigNumberish>,
      discountPercent: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    buyEdgeSubscriptionAdmin(
      toAccount: PromiseOrValue<string>,
      quantity: PromiseOrValue<BigNumberish>,
      discountPercent: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    buyMagic100TokenAdmin(
      toAccount: PromiseOrValue<string>,
      discountPercent: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    buyOracleSubscriptionAdmin(
      toAccount: PromiseOrValue<string>,
      quantity: PromiseOrValue<BigNumberish>,
      discountPercent: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    buySubscriptionAdmin(
      toAccount: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      quantity: PromiseOrValue<BigNumberish>,
      discountPercent: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    buyTraderTokenAdmin(
      toAccount: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      valueType: PromiseOrValue<BigNumberish>,
      discountPercent: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    createSubscription(
      tokenType: PromiseOrValue<BigNumberish>,
      year: PromiseOrValue<BigNumberish>,
      month: PromiseOrValue<BigNumberish>,
      quantity: PromiseOrValue<BigNumberish>,
      min: PromiseOrValue<BigNumberish>,
      max: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getArexaTokenPool(
      _tokenType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { total: BigNumber; sold: BigNumber }>;

    payArexaTokenFromPool(
      poolType: PromiseOrValue<BigNumberish>,
      account: PromiseOrValue<string>,
      quantity: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    buyArexaTokenAdmin(
      toAccount: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      valueType: PromiseOrValue<BigNumberish>,
      discountPercent: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    buyEdgeSubscriptionAdmin(
      toAccount: PromiseOrValue<string>,
      quantity: PromiseOrValue<BigNumberish>,
      discountPercent: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    buyMagic100TokenAdmin(
      toAccount: PromiseOrValue<string>,
      discountPercent: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    buyOracleSubscriptionAdmin(
      toAccount: PromiseOrValue<string>,
      quantity: PromiseOrValue<BigNumberish>,
      discountPercent: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    buySubscriptionAdmin(
      toAccount: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      quantity: PromiseOrValue<BigNumberish>,
      discountPercent: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    buyTraderTokenAdmin(
      toAccount: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      valueType: PromiseOrValue<BigNumberish>,
      discountPercent: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createSubscription(
      tokenType: PromiseOrValue<BigNumberish>,
      year: PromiseOrValue<BigNumberish>,
      month: PromiseOrValue<BigNumberish>,
      quantity: PromiseOrValue<BigNumberish>,
      min: PromiseOrValue<BigNumberish>,
      max: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getArexaTokenPool(
      _tokenType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    payArexaTokenFromPool(
      poolType: PromiseOrValue<BigNumberish>,
      account: PromiseOrValue<string>,
      quantity: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    buyArexaTokenAdmin(
      toAccount: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      valueType: PromiseOrValue<BigNumberish>,
      discountPercent: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    buyEdgeSubscriptionAdmin(
      toAccount: PromiseOrValue<string>,
      quantity: PromiseOrValue<BigNumberish>,
      discountPercent: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    buyMagic100TokenAdmin(
      toAccount: PromiseOrValue<string>,
      discountPercent: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    buyOracleSubscriptionAdmin(
      toAccount: PromiseOrValue<string>,
      quantity: PromiseOrValue<BigNumberish>,
      discountPercent: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    buySubscriptionAdmin(
      toAccount: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      quantity: PromiseOrValue<BigNumberish>,
      discountPercent: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    buyTraderTokenAdmin(
      toAccount: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      valueType: PromiseOrValue<BigNumberish>,
      discountPercent: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createSubscription(
      tokenType: PromiseOrValue<BigNumberish>,
      year: PromiseOrValue<BigNumberish>,
      month: PromiseOrValue<BigNumberish>,
      quantity: PromiseOrValue<BigNumberish>,
      min: PromiseOrValue<BigNumberish>,
      max: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getArexaTokenPool(
      _tokenType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    payArexaTokenFromPool(
      poolType: PromiseOrValue<BigNumberish>,
      account: PromiseOrValue<string>,
      quantity: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
