/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export type ArexaTokenPoolStruct = {
  total: PromiseOrValue<BigNumberish>;
  sold: PromiseOrValue<BigNumberish>;
};

export type ArexaTokenPoolStructOutput = [BigNumber, BigNumber] & {
  total: BigNumber;
  sold: BigNumber;
};

export interface ArexaPlatformAdminFacetInterface extends utils.Interface {
  functions: {
    "buyMagic100TokenAdmin(address)": FunctionFragment;
    "createSubscription(uint256,uint16,uint8,uint256,uint256,uint256)": FunctionFragment;
    "getArexaTokenPool(uint8)": FunctionFragment;
    "payArexaTokenFromPool(uint8,address,uint32)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "buyMagic100TokenAdmin"
      | "createSubscription"
      | "getArexaTokenPool"
      | "payArexaTokenFromPool"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "buyMagic100TokenAdmin",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "createSubscription",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getArexaTokenPool",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "payArexaTokenFromPool",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "buyMagic100TokenAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getArexaTokenPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "payArexaTokenFromPool",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ArexaPlatformAdminFacet extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ArexaPlatformAdminFacetInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    buyMagic100TokenAdmin(
      toAccount: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createSubscription(
      tokenType: PromiseOrValue<BigNumberish>,
      year: PromiseOrValue<BigNumberish>,
      month: PromiseOrValue<BigNumberish>,
      quantity: PromiseOrValue<BigNumberish>,
      min: PromiseOrValue<BigNumberish>,
      max: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getArexaTokenPool(
      _tokenType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[ArexaTokenPoolStructOutput]>;

    payArexaTokenFromPool(
      poolType: PromiseOrValue<BigNumberish>,
      account: PromiseOrValue<string>,
      quantity: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  buyMagic100TokenAdmin(
    toAccount: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createSubscription(
    tokenType: PromiseOrValue<BigNumberish>,
    year: PromiseOrValue<BigNumberish>,
    month: PromiseOrValue<BigNumberish>,
    quantity: PromiseOrValue<BigNumberish>,
    min: PromiseOrValue<BigNumberish>,
    max: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getArexaTokenPool(
    _tokenType: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<ArexaTokenPoolStructOutput>;

  payArexaTokenFromPool(
    poolType: PromiseOrValue<BigNumberish>,
    account: PromiseOrValue<string>,
    quantity: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    buyMagic100TokenAdmin(
      toAccount: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    createSubscription(
      tokenType: PromiseOrValue<BigNumberish>,
      year: PromiseOrValue<BigNumberish>,
      month: PromiseOrValue<BigNumberish>,
      quantity: PromiseOrValue<BigNumberish>,
      min: PromiseOrValue<BigNumberish>,
      max: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getArexaTokenPool(
      _tokenType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<ArexaTokenPoolStructOutput>;

    payArexaTokenFromPool(
      poolType: PromiseOrValue<BigNumberish>,
      account: PromiseOrValue<string>,
      quantity: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    buyMagic100TokenAdmin(
      toAccount: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createSubscription(
      tokenType: PromiseOrValue<BigNumberish>,
      year: PromiseOrValue<BigNumberish>,
      month: PromiseOrValue<BigNumberish>,
      quantity: PromiseOrValue<BigNumberish>,
      min: PromiseOrValue<BigNumberish>,
      max: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getArexaTokenPool(
      _tokenType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    payArexaTokenFromPool(
      poolType: PromiseOrValue<BigNumberish>,
      account: PromiseOrValue<string>,
      quantity: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    buyMagic100TokenAdmin(
      toAccount: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createSubscription(
      tokenType: PromiseOrValue<BigNumberish>,
      year: PromiseOrValue<BigNumberish>,
      month: PromiseOrValue<BigNumberish>,
      quantity: PromiseOrValue<BigNumberish>,
      min: PromiseOrValue<BigNumberish>,
      max: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getArexaTokenPool(
      _tokenType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    payArexaTokenFromPool(
      poolType: PromiseOrValue<BigNumberish>,
      account: PromiseOrValue<string>,
      quantity: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
