/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface IERC1155PausableInterface extends utils.Interface {
  functions: {
    "pauseAllToken()": FunctionFragment;
    "pauseToken(uint256)": FunctionFragment;
    "unpauseAllToken()": FunctionFragment;
    "unpauseToken(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "pauseAllToken"
      | "pauseToken"
      | "unpauseAllToken"
      | "unpauseToken"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "pauseAllToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pauseToken",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "unpauseAllToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "unpauseToken",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "pauseAllToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pauseToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unpauseAllToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unpauseToken",
    data: BytesLike
  ): Result;

  events: {
    "AllTokenPaused(address)": EventFragment;
    "AllTokenUnpaused(address)": EventFragment;
    "TokenPaused(address,uint256)": EventFragment;
    "TokenUnpaused(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AllTokenPaused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AllTokenUnpaused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenPaused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenUnpaused"): EventFragment;
}

export interface AllTokenPausedEventObject {
  account: string;
}
export type AllTokenPausedEvent = TypedEvent<
  [string],
  AllTokenPausedEventObject
>;

export type AllTokenPausedEventFilter = TypedEventFilter<AllTokenPausedEvent>;

export interface AllTokenUnpausedEventObject {
  account: string;
}
export type AllTokenUnpausedEvent = TypedEvent<
  [string],
  AllTokenUnpausedEventObject
>;

export type AllTokenUnpausedEventFilter =
  TypedEventFilter<AllTokenUnpausedEvent>;

export interface TokenPausedEventObject {
  account: string;
  tokenId: BigNumber;
}
export type TokenPausedEvent = TypedEvent<
  [string, BigNumber],
  TokenPausedEventObject
>;

export type TokenPausedEventFilter = TypedEventFilter<TokenPausedEvent>;

export interface TokenUnpausedEventObject {
  account: string;
  tokenId: BigNumber;
}
export type TokenUnpausedEvent = TypedEvent<
  [string, BigNumber],
  TokenUnpausedEventObject
>;

export type TokenUnpausedEventFilter = TypedEventFilter<TokenUnpausedEvent>;

export interface IERC1155Pausable extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IERC1155PausableInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    pauseAllToken(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    pauseToken(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    unpauseAllToken(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    unpauseToken(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  pauseAllToken(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  pauseToken(
    tokenId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  unpauseAllToken(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  unpauseToken(
    tokenId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    pauseAllToken(overrides?: CallOverrides): Promise<void>;

    pauseToken(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    unpauseAllToken(overrides?: CallOverrides): Promise<void>;

    unpauseToken(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "AllTokenPaused(address)"(
      account?: PromiseOrValue<string> | null
    ): AllTokenPausedEventFilter;
    AllTokenPaused(
      account?: PromiseOrValue<string> | null
    ): AllTokenPausedEventFilter;

    "AllTokenUnpaused(address)"(
      account?: PromiseOrValue<string> | null
    ): AllTokenUnpausedEventFilter;
    AllTokenUnpaused(
      account?: PromiseOrValue<string> | null
    ): AllTokenUnpausedEventFilter;

    "TokenPaused(address,uint256)"(
      account?: PromiseOrValue<string> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null
    ): TokenPausedEventFilter;
    TokenPaused(
      account?: PromiseOrValue<string> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null
    ): TokenPausedEventFilter;

    "TokenUnpaused(address,uint256)"(
      account?: PromiseOrValue<string> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null
    ): TokenUnpausedEventFilter;
    TokenUnpaused(
      account?: PromiseOrValue<string> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null
    ): TokenUnpausedEventFilter;
  };

  estimateGas: {
    pauseAllToken(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    pauseToken(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    unpauseAllToken(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    unpauseToken(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    pauseAllToken(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    pauseToken(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    unpauseAllToken(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    unpauseToken(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
