/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as base from "./base";
export type { base };
export type { IERC1155 } from "./IERC1155";
export type { IERC1155Allowance } from "./IERC1155Allowance";
export type { IERC1155Enumerable } from "./IERC1155Enumerable";
export type { IERC1155MetadataURI } from "./IERC1155MetadataURI";
export type { IERC1155Pausable } from "./IERC1155Pausable";
export type { IERC1155Receiver } from "./IERC1155Receiver";
