/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as base from "./base";
export { IERC1155__factory } from "./IERC1155__factory";
export { IERC1155Allowance__factory } from "./IERC1155Allowance__factory";
export { IERC1155Enumerable__factory } from "./IERC1155Enumerable__factory";
export { IERC1155MetadataURI__factory } from "./IERC1155MetadataURI__factory";
export { IERC1155Pausable__factory } from "./IERC1155Pausable__factory";
export { IERC1155Receiver__factory } from "./IERC1155Receiver__factory";
