/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IERC20ExtendedInternal,
  IERC20ExtendedInternalInterface,
} from "../../../../base/ERC20/extended/IERC20ExtendedInternal";

const _abi = [
  {
    inputs: [],
    name: "ERC20Extended__ExcessiveAllowance",
    type: "error",
  },
  {
    inputs: [],
    name: "ERC20Extended__InsufficientAllowance",
    type: "error",
  },
] as const;

export class IERC20ExtendedInternal__factory {
  static readonly abi = _abi;
  static createInterface(): IERC20ExtendedInternalInterface {
    return new utils.Interface(_abi) as IERC20ExtendedInternalInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC20ExtendedInternal {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IERC20ExtendedInternal;
  }
}
