/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ArexaDiamondDummyImplementation } from "./ArexaDiamondDummyImplementation";
export type { TokenDiamondDummyImplementation } from "./TokenDiamondDummyImplementation";
