/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, Signer, utils } from "ethers";
import type { EventFragment } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface LibBlackWhiteListInterface extends utils.Interface {
  functions: {};

  events: {
    "AccountBlackWhiteList(bytes32,address,bool)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AccountBlackWhiteList"): EventFragment;
}

export interface AccountBlackWhiteListEventObject {
  _target: string;
  _account: string;
  _lockValue: boolean;
}
export type AccountBlackWhiteListEvent = TypedEvent<
  [string, string, boolean],
  AccountBlackWhiteListEventObject
>;

export type AccountBlackWhiteListEventFilter =
  TypedEventFilter<AccountBlackWhiteListEvent>;

export interface LibBlackWhiteList extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: LibBlackWhiteListInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {};

  callStatic: {};

  filters: {
    "AccountBlackWhiteList(bytes32,address,bool)"(
      _target?: PromiseOrValue<BytesLike> | null,
      _account?: PromiseOrValue<string> | null,
      _lockValue?: null
    ): AccountBlackWhiteListEventFilter;
    AccountBlackWhiteList(
      _target?: PromiseOrValue<BytesLike> | null,
      _account?: PromiseOrValue<string> | null,
      _lockValue?: null
    ): AccountBlackWhiteListEventFilter;
  };

  estimateGas: {};

  populateTransaction: {};
}
