/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, Signer, utils } from "ethers";
import type { EventFragment } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface LibTargetedPausableInterface extends utils.Interface {
  functions: {};

  events: {
    "TargetedPaused(bytes32,address)": EventFragment;
    "TargetedUnpaused(bytes32,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "TargetedPaused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TargetedUnpaused"): EventFragment;
}

export interface TargetedPausedEventObject {
  target: string;
  account: string;
}
export type TargetedPausedEvent = TypedEvent<
  [string, string],
  TargetedPausedEventObject
>;

export type TargetedPausedEventFilter = TypedEventFilter<TargetedPausedEvent>;

export interface TargetedUnpausedEventObject {
  target: string;
  account: string;
}
export type TargetedUnpausedEvent = TypedEvent<
  [string, string],
  TargetedUnpausedEventObject
>;

export type TargetedUnpausedEventFilter =
  TypedEventFilter<TargetedUnpausedEvent>;

export interface LibTargetedPausable extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: LibTargetedPausableInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {};

  callStatic: {};

  filters: {
    "TargetedPaused(bytes32,address)"(
      target?: PromiseOrValue<BytesLike> | null,
      account?: PromiseOrValue<string> | null
    ): TargetedPausedEventFilter;
    TargetedPaused(
      target?: PromiseOrValue<BytesLike> | null,
      account?: PromiseOrValue<string> | null
    ): TargetedPausedEventFilter;

    "TargetedUnpaused(bytes32,address)"(
      target?: null,
      account?: PromiseOrValue<string> | null
    ): TargetedUnpausedEventFilter;
    TargetedUnpaused(
      target?: null,
      account?: PromiseOrValue<string> | null
    ): TargetedUnpausedEventFilter;
  };

  estimateGas: {};

  populateTransaction: {};
}
