/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ArexaDiamondDummyImplementation__factory } from "./ArexaDiamondDummyImplementation__factory";
export { TokenDiamondDummyImplementation__factory } from "./TokenDiamondDummyImplementation__factory";
