/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  LibTargetedPausable,
  LibTargetedPausableInterface,
} from "../../../base/TargetedPausable/LibTargetedPausable";

const _abi = [
  {
    inputs: [],
    name: "TargetedPausable__NotTargetedPaused",
    type: "error",
  },
  {
    inputs: [],
    name: "TargetedPausable__TargetedPaused",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "target",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "TargetedPaused",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bytes32",
        name: "target",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "TargetedUnpaused",
    type: "event",
  },
] as const;

const _bytecode =
  "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220c2954caf9af1bc520cd0c3e4dd10c5c1c8a4bef462213c1a88f96427a7a88efe64736f6c63430008110033";

type LibTargetedPausableConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: LibTargetedPausableConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class LibTargetedPausable__factory extends ContractFactory {
  constructor(...args: LibTargetedPausableConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<LibTargetedPausable> {
    return super.deploy(overrides || {}) as Promise<LibTargetedPausable>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): LibTargetedPausable {
    return super.attach(address) as LibTargetedPausable;
  }
  override connect(signer: Signer): LibTargetedPausable__factory {
    return super.connect(signer) as LibTargetedPausable__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): LibTargetedPausableInterface {
    return new utils.Interface(_abi) as LibTargetedPausableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): LibTargetedPausable {
    return new Contract(address, _abi, signerOrProvider) as LibTargetedPausable;
  }
}
