/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ArexaPlatformDiamondInit } from "./ArexaPlatformDiamondInit";
export type { ArexaTokenDiamondInit } from "./ArexaTokenDiamondInit";
