/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  LibDiamondEtherscan,
  LibDiamondEtherscanInterface,
} from "../../../base/Diamond/LibDiamondEtherscan";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "implementation",
        type: "address",
      },
    ],
    name: "Upgraded",
    type: "event",
  },
] as const;

const _bytecode =
  "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220698901cc5e1bc6a607718711a7e7664809adfc7e59522bae627ecf080059ae3e64736f6c63430008110033";

type LibDiamondEtherscanConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: LibDiamondEtherscanConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class LibDiamondEtherscan__factory extends ContractFactory {
  constructor(...args: LibDiamondEtherscanConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<LibDiamondEtherscan> {
    return super.deploy(overrides || {}) as Promise<LibDiamondEtherscan>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): LibDiamondEtherscan {
    return super.attach(address) as LibDiamondEtherscan;
  }
  override connect(signer: Signer): LibDiamondEtherscan__factory {
    return super.connect(signer) as LibDiamondEtherscan__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): LibDiamondEtherscanInterface {
    return new utils.Interface(_abi) as LibDiamondEtherscanInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): LibDiamondEtherscan {
    return new Contract(address, _abi, signerOrProvider) as LibDiamondEtherscan;
  }
}
