/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ArexaPlatformDiamondInit__factory } from "./ArexaPlatformDiamondInit__factory";
export { ArexaTokenDiamondInit__factory } from "./ArexaTokenDiamondInit__factory";
