/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export interface LibArexaPlatformInterface extends utils.Interface {
  functions: {
    "AMOUNT_VALUE_TYPE()": FunctionFragment;
    "QUANTITY_VALUE_TYPE()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "AMOUNT_VALUE_TYPE" | "QUANTITY_VALUE_TYPE"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "AMOUNT_VALUE_TYPE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "QUANTITY_VALUE_TYPE",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "AMOUNT_VALUE_TYPE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "QUANTITY_VALUE_TYPE",
    data: BytesLike
  ): Result;

  events: {};
}

export interface LibArexaPlatform extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: LibArexaPlatformInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    AMOUNT_VALUE_TYPE(overrides?: CallOverrides): Promise<[number]>;

    QUANTITY_VALUE_TYPE(overrides?: CallOverrides): Promise<[number]>;
  };

  AMOUNT_VALUE_TYPE(overrides?: CallOverrides): Promise<number>;

  QUANTITY_VALUE_TYPE(overrides?: CallOverrides): Promise<number>;

  callStatic: {
    AMOUNT_VALUE_TYPE(overrides?: CallOverrides): Promise<number>;

    QUANTITY_VALUE_TYPE(overrides?: CallOverrides): Promise<number>;
  };

  filters: {};

  estimateGas: {
    AMOUNT_VALUE_TYPE(overrides?: CallOverrides): Promise<BigNumber>;

    QUANTITY_VALUE_TYPE(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    AMOUNT_VALUE_TYPE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    QUANTITY_VALUE_TYPE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
